base_url = "https://www.sereno.insure"

title = "Sereno - Weather Parametric Insurance"
description = "Fast, transparent parametric insurance covering weather-related business disruptions. Built by meteorologists for SMEs across Europe."

default_language = "en"

minify_html = true
compile_sass = true
build_search_index = false

[slugify]
paths = "on"
taxonomies = "on" 
anchors = "on"

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
author = "Sereno"
keywords = " parametric weather insurance, weather risk insurance, weather protection, meteorological insurance, weather-sensibility protection, European business insurance, maritime insurance, construction insurance, outdoor events insurance, mobility insurance, climate-related financial protection"
